export const countries = new Map([
	["1", { country: "United States", countryCode: "1", startsWith: "1", ISOCode: "US"}],
	["1", { country: "Canada", countryCode: "1", startsWith: "1", ISOCode: "CA"}],
	["7", { country: "Russia", countryCode: "7", startsWith: "7", ISOCode: "RU"}],
	["7", { country: "Kazakhstan", countryCode: "7", startsWith: "7", ISOCode: "KZ"}],
	["20", { country: "Egypt", countryCode: "20", startsWith: "20", ISOCode: "EG"}],
	["27", { country: "South Africa", countryCode: "27", startsWith: "27", ISOCode: "ZA"}],
	["30", { country: "Greece", countryCode: "30", startsWith: "30", ISOCode: "GR"}],
	["31", { country: "Netherlands", countryCode: "31", startsWith: "31", ISOCode: "NL"}],
	["32", { country: "Belgium", countryCode: "32", startsWith: "32", ISOCode: "BE"}],
	["33", { country: "France", countryCode: "33", startsWith: "33", ISOCode: "FR"}],
	["34", { country: "Spain", countryCode: "34", startsWith: "34", ISOCode: "ES"}],
	["36", { country: "Hungary", countryCode: "36", startsWith: "36", ISOCode: "HU"}],
	["39", { country: "Italy", countryCode: "39", startsWith: "39", ISOCode: "IT"}],
	["40", { country: "Romania", countryCode: "40", startsWith: "40", ISOCode: "RO"}],
	["41", { country: "Switzerland", countryCode: "41", startsWith: "41", ISOCode: "CH"}],
	["43", { country: "Austria", countryCode: "43", startsWith: "43", ISOCode: "AT"}],
	["44", { country: "United Kingdom", countryCode: "44", startsWith: "44", ISOCode: "GB"}],
	["45", { country: "Denmark", countryCode: "45", startsWith: "45", ISOCode: "DK"}],
	["46", { country: "Sweden", countryCode: "46", startsWith: "46", ISOCode: "SE"}],
	["47", { country: "Svalbard and Jan Mayen", countryCode: "47", startsWith: "47", ISOCode: "SJ"}],
	["47", { country: "Norway", countryCode: "47", startsWith: "47", ISOCode: "NO"}],
	["48", { country: "Poland", countryCode: "48", startsWith: "48", ISOCode: "PL"}],
	["49", { country: "Germany", countryCode: "49", startsWith: "49", ISOCode: "DE"}],
	["51", { country: "Peru", countryCode: "51", startsWith: "51", ISOCode: "PE"}],
	["52", { country: "Mexico", countryCode: "52", startsWith: "52", ISOCode: "MX"}],
	["53", { country: "Cuba", countryCode: "53", startsWith: "53", ISOCode: "CU"}],
	["54", { country: "Argentina", countryCode: "54", startsWith: "54", ISOCode: "AR"}],
	["55", { country: "Brazil", countryCode: "55", startsWith: "55", ISOCode: "BR"}],
	["56", { country: "Chile", countryCode: "56", startsWith: "56", ISOCode: "CL"}],
	["57", { country: "Colombia", countryCode: "57", startsWith: "57", ISOCode: "CO"}],
	["58", { country: "Venezuela", countryCode: "58", startsWith: "58", ISOCode: "VE"}],
	["60", { country: "Malaysia", countryCode: "60", startsWith: "60", ISOCode: "MY"}],
	["61", { country: "Cocos Islands", countryCode: "61", startsWith: "61", ISOCode: "CC"}],
	["61", { country: "Christmas Island", countryCode: "61", startsWith: "61", ISOCode: "CX"}],
	["61", { country: "Australia", countryCode: "61", startsWith: "61", ISOCode: "AU"}],
	["62", { country: "Indonesia", countryCode: "62", startsWith: "62", ISOCode: "ID"}],
	["63", { country: "Philippines", countryCode: "63", startsWith: "63", ISOCode: "PH"}],
	["64", { country: "Pitcairn", countryCode: "64", startsWith: "64", ISOCode: "PN"}],
	["64", { country: "New Zealand", countryCode: "64", startsWith: "64", ISOCode: "NZ"}],
	["65", { country: "Singapore", countryCode: "65", startsWith: "65", ISOCode: "SG"}],
	["66", { country: "Thailand", countryCode: "66", startsWith: "66", ISOCode: "TH"}],
	["81", { country: "Japan", countryCode: "81", startsWith: "81", ISOCode: "JP"}],
	["82", { country: "South Korea", countryCode: "82", startsWith: "82", ISOCode: "KR"}],
	["84", { country: "Vietnam", countryCode: "84", startsWith: "84", ISOCode: "VN"}],
	["86", { country: "China", countryCode: "86", startsWith: "86", ISOCode: "CN"}],
	["90", { country: "Turkey", countryCode: "90", startsWith: "90", ISOCode: "TR"}],
	["91", { country: "India", countryCode: "91", startsWith: "91", ISOCode: "IN"}],
	["92", { country: "Pakistan", countryCode: "92", startsWith: "92", ISOCode: "PK"}],
	["93", { country: "Afghanistan", countryCode: "93", startsWith: "93", ISOCode: "AF"}],
	["94", { country: "Sri Lanka", countryCode: "94", startsWith: "94", ISOCode: "LK"}],
	["95", { country: "Myanmar", countryCode: "95", startsWith: "95", ISOCode: "MM"}],
	["98", { country: "Iran", countryCode: "98", startsWith: "98", ISOCode: "IR"}],
	["211", { country: "South Sudan", countryCode: "211", startsWith: "211", ISOCode: "SS"}],
	["212", { country: "Western Sahara", countryCode: "212", startsWith: "212", ISOCode: "EH"}],
	["212", { country: "Morocco", countryCode: "212", startsWith: "212", ISOCode: "MA"}],
	["213", { country: "Algeria", countryCode: "213", startsWith: "213", ISOCode: "DZ"}],
	["216", { country: "Tunisia", countryCode: "216", startsWith: "216", ISOCode: "TN"}],
	["218", { country: "Libya", countryCode: "218", startsWith: "218", ISOCode: "LY"}],
	["220", { country: "Gambia", countryCode: "220", startsWith: "220", ISOCode: "GM"}],
	["221", { country: "Senegal", countryCode: "221", startsWith: "221", ISOCode: "SN"}],
	["222", { country: "Mauritania", countryCode: "222", startsWith: "222", ISOCode: "MR"}],
	["223", { country: "Mali", countryCode: "223", startsWith: "223", ISOCode: "ML"}],
	["224", { country: "Guinea", countryCode: "224", startsWith: "224", ISOCode: "GN"}],
	["225", { country: "Ivory Coast", countryCode: "225", startsWith: "225", ISOCode: "CI"}],
	["226", { country: "Burkina Faso", countryCode: "226", startsWith: "226", ISOCode: "BF"}],
	["227", { country: "Niger", countryCode: "227", startsWith: "227", ISOCode: "NE"}],
	["228", { country: "Togo", countryCode: "228", startsWith: "228", ISOCode: "TG"}],
	["229", { country: "Benin", countryCode: "229", startsWith: "229", ISOCode: "BJ"}],
	["230", { country: "Mauritius", countryCode: "230", startsWith: "230", ISOCode: "MU"}],
	["231", { country: "Liberia", countryCode: "231", startsWith: "231", ISOCode: "LR"}],
	["232", { country: "Sierra Leone", countryCode: "232", startsWith: "232", ISOCode: "SL"}],
	["233", { country: "Ghana", countryCode: "233", startsWith: "233", ISOCode: "GH"}],
	["234", { country: "Nigeria", countryCode: "234", startsWith: "234", ISOCode: "NG"}],
	["235", { country: "Chad", countryCode: "235", startsWith: "235", ISOCode: "TD"}],
	["236", { country: "Central African Republic", countryCode: "236", startsWith: "236", ISOCode: "CF"}],
	["237", { country: "Cameroon", countryCode: "237", startsWith: "237", ISOCode: "CM"}],
	["238", { country: "Cape Verde", countryCode: "238", startsWith: "238", ISOCode: "CV"}],
	["239", { country: "Sao Tome and Principe", countryCode: "239", startsWith: "239", ISOCode: "ST"}],
	["240", { country: "Equatorial Guinea", countryCode: "240", startsWith: "240", ISOCode: "GQ"}],
	["241", { country: "Gabon", countryCode: "241", startsWith: "241", ISOCode: "GA"}],
	["242", { country: "Republic of the Congo", countryCode: "242", startsWith: "242", ISOCode: "CG"}],
	["243", { country: "Democratic Republic of the Congo", countryCode: "243", startsWith: "243", ISOCode: "CD"}],
	["244", { country: "Angola", countryCode: "244", startsWith: "244", ISOCode: "AO"}],
	["245", { country: "Guinea-Bissau", countryCode: "245", startsWith: "245", ISOCode: "GW"}],
	["246", { country: "British Indian Ocean Territory", countryCode: "246", startsWith: "246", ISOCode: "IO"}],
	["248", { country: "Seychelles", countryCode: "248", startsWith: "248", ISOCode: "SC"}],
	["249", { country: "Sudan", countryCode: "249", startsWith: "249", ISOCode: "SD"}],
	["250", { country: "Rwanda", countryCode: "250", startsWith: "250", ISOCode: "RW"}],
	["251", { country: "Ethiopia", countryCode: "251", startsWith: "251", ISOCode: "ET"}],
	["252", { country: "Somalia", countryCode: "252", startsWith: "252", ISOCode: "SO"}],
	["253", { country: "Djibouti", countryCode: "253", startsWith: "253", ISOCode: "DJ"}],
	["254", { country: "Kenya", countryCode: "254", startsWith: "254", ISOCode: "KE"}],
	["255", { country: "Tanzania", countryCode: "255", startsWith: "255", ISOCode: "TZ"}],
	["256", { country: "Uganda", countryCode: "256", startsWith: "256", ISOCode: "UG"}],
	["257", { country: "Burundi", countryCode: "257", startsWith: "257", ISOCode: "BI"}],
	["258", { country: "Mozambique", countryCode: "258", startsWith: "258", ISOCode: "MZ"}],
	["260", { country: "Zambia", countryCode: "260", startsWith: "260", ISOCode: "ZM"}],
	["261", { country: "Madagascar", countryCode: "261", startsWith: "261", ISOCode: "MG"}],
	["262", { country: "Reunion", countryCode: "262", startsWith: "262", ISOCode: "RE"}],
	["262", { country: "Mayotte", countryCode: "262", startsWith: "262", ISOCode: "YT"}],
	["263", { country: "Zimbabwe", countryCode: "263", startsWith: "263", ISOCode: "ZW"}],
	["264", { country: "Namibia", countryCode: "264", startsWith: "264", ISOCode: "NA"}],
	["265", { country: "Malawi", countryCode: "265", startsWith: "265", ISOCode: "MW"}],
	["266", { country: "Lesotho", countryCode: "266", startsWith: "266", ISOCode: "LS"}],
	["267", { country: "Botswana", countryCode: "267", startsWith: "267", ISOCode: "BW"}],
	["268", { country: "Swaziland", countryCode: "268", startsWith: "268", ISOCode: "SZ"}],
	["269", { country: "Comoros", countryCode: "269", startsWith: "269", ISOCode: "KM"}],
	["290", { country: "Saint Helena", countryCode: "290", startsWith: "290", ISOCode: "SH"}],
	["291", { country: "Eritrea", countryCode: "291", startsWith: "291", ISOCode: "ER"}],
	["297", { country: "Aruba", countryCode: "297", startsWith: "297", ISOCode: "AW"}],
	["298", { country: "Faroe Islands", countryCode: "298", startsWith: "298", ISOCode: "FO"}],
	["299", { country: "Greenland", countryCode: "299", startsWith: "299", ISOCode: "GL"}],
	["350", { country: "Gibraltar", countryCode: "350", startsWith: "350", ISOCode: "GI"}],
	["351", { country: "Portugal", countryCode: "351", startsWith: "351", ISOCode: "PT"}],
	["352", { country: "Luxembourg", countryCode: "352", startsWith: "352", ISOCode: "LU"}],
	["353", { country: "Ireland", countryCode: "353", startsWith: "353", ISOCode: "IE"}],
	["354", { country: "Iceland", countryCode: "354", startsWith: "354", ISOCode: "IS"}],
	["355", { country: "Albania", countryCode: "355", startsWith: "355", ISOCode: "AL"}],
	["356", { country: "Malta", countryCode: "356", startsWith: "356", ISOCode: "MT"}],
	["357", { country: "Cyprus", countryCode: "357", startsWith: "357", ISOCode: "CY"}],
	["358", { country: "Finland", countryCode: "358", startsWith: "358", ISOCode: "FI"}],
	["359", { country: "Bulgaria", countryCode: "359", startsWith: "359", ISOCode: "BG"}],
	["370", { country: "Lithuania", countryCode: "370", startsWith: "370", ISOCode: "LT"}],
	["371", { country: "Latvia", countryCode: "371", startsWith: "371", ISOCode: "LV"}],
	["372", { country: "Estonia", countryCode: "372", startsWith: "372", ISOCode: "EE"}],
	["373", { country: "Moldova", countryCode: "373", startsWith: "373", ISOCode: "MD"}],
	["374", { country: "Armenia", countryCode: "374", startsWith: "374", ISOCode: "AM"}],
	["375", { country: "Belarus", countryCode: "375", startsWith: "375", ISOCode: "BY"}],
	["376", { country: "Andorra", countryCode: "376", startsWith: "376", ISOCode: "AD"}],
	["377", { country: "Monaco", countryCode: "377", startsWith: "377", ISOCode: "MC"}],
	["378", { country: "San Marino", countryCode: "378", startsWith: "378", ISOCode: "SM"}],
	["379", { country: "Vatican", countryCode: "379", startsWith: "379", ISOCode: "VA"}],
	["380", { country: "Ukraine", countryCode: "380", startsWith: "380", ISOCode: "UA"}],
	["381", { country: "Serbia", countryCode: "381", startsWith: "381", ISOCode: "RS"}],
	["382", { country: "Montenegro", countryCode: "382", startsWith: "382", ISOCode: "ME"}],
	["383", { country: "Kosovo", countryCode: "383", startsWith: "383", ISOCode: "XK"}],
	["385", { country: "Croatia", countryCode: "385", startsWith: "385", ISOCode: "HR"}],
	["386", { country: "Slovenia", countryCode: "386", startsWith: "386", ISOCode: "SI"}],
	["387", { country: "Bosnia and Herzegovina", countryCode: "387", startsWith: "387", ISOCode: "BA"}],
	["389", { country: "Macedonia", countryCode: "389", startsWith: "389", ISOCode: "MK"}],
	["420", { country: "Czech Republic", countryCode: "420", startsWith: "420", ISOCode: "CZ"}],
	["421", { country: "Slovakia", countryCode: "421", startsWith: "421", ISOCode: "SK"}],
	["423", { country: "Liechtenstein", countryCode: "423", startsWith: "423", ISOCode: "LI"}],
	["500", { country: "Falkland Islands", countryCode: "500", startsWith: "500", ISOCode: "FK"}],
	["501", { country: "Belize", countryCode: "501", startsWith: "501", ISOCode: "BZ"}],
	["502", { country: "Guatemala", countryCode: "502", startsWith: "502", ISOCode: "GT"}],
	["503", { country: "El Salvador", countryCode: "503", startsWith: "503", ISOCode: "SV"}],
	["504", { country: "Honduras", countryCode: "504", startsWith: "504", ISOCode: "HN"}],
	["505", { country: "Nicaragua", countryCode: "505", startsWith: "505", ISOCode: "NI"}],
	["506", { country: "Costa Rica", countryCode: "506", startsWith: "506", ISOCode: "CR"}],
	["507", { country: "Panama", countryCode: "507", startsWith: "507", ISOCode: "PA"}],
	["508", { country: "Saint Pierre and Miquelon", countryCode: "508", startsWith: "508", ISOCode: "PM"}],
	["509", { country: "Haiti", countryCode: "509", startsWith: "509", ISOCode: "HT"}],
	["590", { country: "Saint Martin", countryCode: "590", startsWith: "590", ISOCode: "MF"}],
	["590", { country: "Saint Barthelemy", countryCode: "590", startsWith: "590", ISOCode: "BL"}],
	["591", { country: "Bolivia", countryCode: "591", startsWith: "591", ISOCode: "BO"}],
	["592", { country: "Guyana", countryCode: "592", startsWith: "592", ISOCode: "GY"}],
	["593", { country: "Ecuador", countryCode: "593", startsWith: "593", ISOCode: "EC"}],
	["595", { country: "Paraguay", countryCode: "595", startsWith: "595", ISOCode: "PY"}],
	["597", { country: "Suriname", countryCode: "597", startsWith: "597", ISOCode: "SR"}],
	["598", { country: "Uruguay", countryCode: "598", startsWith: "598", ISOCode: "UY"}],
	["599", { country: "Netherlands Antilles", countryCode: "599", startsWith: "599", ISOCode: "AN"}],
	["599", { country: "Curacao", countryCode: "599", startsWith: "599", ISOCode: "CW"}],
	["670", { country: "East Timor", countryCode: "670", startsWith: "670", ISOCode: "TL"}],
	["672", { country: "Antarctica", countryCode: "672", startsWith: "672", ISOCode: "AQ"}],
	["673", { country: "Brunei", countryCode: "673", startsWith: "673", ISOCode: "BN"}],
	["674", { country: "Nauru", countryCode: "674", startsWith: "674", ISOCode: "NR"}],
	["675", { country: "Papua New Guinea", countryCode: "675", startsWith: "675", ISOCode: "PG"}],
	["676", { country: "Tonga", countryCode: "676", startsWith: "676", ISOCode: "TO"}],
	["677", { country: "Solomon Islands", countryCode: "677", startsWith: "677", ISOCode: "SB"}],
	["678", { country: "Vanuatu", countryCode: "678", startsWith: "678", ISOCode: "VU"}],
	["679", { country: "Fiji", countryCode: "679", startsWith: "679", ISOCode: "FJ"}],
	["680", { country: "Palau", countryCode: "680", startsWith: "680", ISOCode: "PW"}],
	["681", { country: "Wallis and Futuna", countryCode: "681", startsWith: "681", ISOCode: "WF"}],
	["682", { country: "Cook Islands", countryCode: "682", startsWith: "682", ISOCode: "CK"}],
	["683", { country: "Niue", countryCode: "683", startsWith: "683", ISOCode: "NU"}],
	["685", { country: "Samoa", countryCode: "685", startsWith: "685", ISOCode: "WS"}],
	["686", { country: "Kiribati", countryCode: "686", startsWith: "686", ISOCode: "KI"}],
	["687", { country: "New Caledonia", countryCode: "687", startsWith: "687", ISOCode: "NC"}],
	["688", { country: "Tuvalu", countryCode: "688", startsWith: "688", ISOCode: "TV"}],
	["689", { country: "French Polynesia", countryCode: "689", startsWith: "689", ISOCode: "PF"}],
	["690", { country: "Tokelau", countryCode: "690", startsWith: "690", ISOCode: "TK"}],
	["691", { country: "Micronesia", countryCode: "691", startsWith: "691", ISOCode: "FM"}],
	["692", { country: "Marshall Islands", countryCode: "692", startsWith: "692", ISOCode: "MH"}],
	["850", { country: "North Korea", countryCode: "850", startsWith: "850", ISOCode: "KP"}],
	["852", { country: "Hong Kong", countryCode: "852", startsWith: "852", ISOCode: "HK"}],
	["853", { country: "Macau", countryCode: "853", startsWith: "853", ISOCode: "MO"}],
	["855", { country: "Cambodia", countryCode: "855", startsWith: "855", ISOCode: "KH"}],
	["856", { country: "Laos", countryCode: "856", startsWith: "856", ISOCode: "LA"}],
	["880", { country: "Bangladesh", countryCode: "880", startsWith: "880", ISOCode: "BD"}],
	["886", { country: "Taiwan", countryCode: "886", startsWith: "886", ISOCode: "TW"}],
	["960", { country: "Maldives", countryCode: "960", startsWith: "960", ISOCode: "MV"}],
	["961", { country: "Lebanon", countryCode: "961", startsWith: "961", ISOCode: "LB"}],
	["962", { country: "Jordan", countryCode: "962", startsWith: "962", ISOCode: "JO"}],
	["963", { country: "Syria", countryCode: "963", startsWith: "963", ISOCode: "SY"}],
	["964", { country: "Iraq", countryCode: "964", startsWith: "964", ISOCode: "IQ"}],
	["965", { country: "Kuwait", countryCode: "965", startsWith: "965", ISOCode: "KW"}],
	["966", { country: "Saudi Arabia", countryCode: "966", startsWith: "966", ISOCode: "SA"}],
	["967", { country: "Yemen", countryCode: "967", startsWith: "967", ISOCode: "YE"}],
	["968", { country: "Oman", countryCode: "968", startsWith: "968", ISOCode: "OM"}],
	["970", { country: "Palestine", countryCode: "970", startsWith: "970", ISOCode: "PS"}],
	["971", { country: "United Arab Emirates", countryCode: "971", startsWith: "971", ISOCode: "AE"}],
	["972", { country: "Israel", countryCode: "972", startsWith: "972", ISOCode: "IL"}],
	["973", { country: "Bahrain", countryCode: "973", startsWith: "973", ISOCode: "BH"}],
	["974", { country: "Qatar", countryCode: "974", startsWith: "974", ISOCode: "QA"}],
	["975", { country: "Bhutan", countryCode: "975", startsWith: "975", ISOCode: "BT"}],
	["976", { country: "Mongolia", countryCode: "976", startsWith: "976", ISOCode: "MN"}],
	["977", { country: "Nepal", countryCode: "977", startsWith: "977", ISOCode: "NP"}],
	["992", { country: "Tajikistan", countryCode: "992", startsWith: "992", ISOCode: "TJ"}],
	["993", { country: "Turkmenistan", countryCode: "993", startsWith: "993", ISOCode: "TM"}],
	["994", { country: "Azerbaijan", countryCode: "994", startsWith: "994", ISOCode: "AZ"}],
	["995", { country: "Georgia", countryCode: "995", startsWith: "995", ISOCode: "GE"}],
	["996", { country: "Kyrgyzstan", countryCode: "996", startsWith: "996", ISOCode: "KG"}],
	["998", { country: "Uzbekistan", countryCode: "998", startsWith: "998", ISOCode: "UZ"}],
	["1242", { country: "Bahamas", countryCode: "1-242", startsWith: "1242", ISOCode: "BS"}],
	["1246", { country: "Barbados", countryCode: "1-246", startsWith: "1246", ISOCode: "BB"}],
	["1264", { country: "Anguilla", countryCode: "1-264", startsWith: "1264", ISOCode: "AI"}],
	["1268", { country: "Antigua and Barbuda", countryCode: "1-268", startsWith: "1268", ISOCode: "AG"}],
	["1284", { country: "British Virgin Islands", countryCode: "1-284", startsWith: "1284", ISOCode: "VG"}],
	["1340", { country: "U.S. Virgin Islands", countryCode: "1-340", startsWith: "1340", ISOCode: "VI"}],
	["1345", { country: "Cayman Islands", countryCode: "1-345", startsWith: "1345", ISOCode: "KY"}],
	["1441", { country: "Bermuda", countryCode: "1-441", startsWith: "1441", ISOCode: "BM"}],
	["1473", { country: "Grenada", countryCode: "1-473", startsWith: "1473", ISOCode: "GD"}],
	["1649", { country: "Turks and Caicos Islands", countryCode: "1-649", startsWith: "1649", ISOCode: "TC"}],
	["1664", { country: "Montserrat", countryCode: "1-664", startsWith: "1664", ISOCode: "MS"}],
	["1670", { country: "Northern Mariana Islands", countryCode: "1-670", startsWith: "1670", ISOCode: "MP"}],
	["1671", { country: "Guam", countryCode: "1-671", startsWith: "1671", ISOCode: "GU"}],
	["1684", { country: "American Samoa", countryCode: "1-684", startsWith: "1684", ISOCode: "AS"}],
	["1721", { country: "Sint Maarten", countryCode: "1-721", startsWith: "1721", ISOCode: "SX"}],
	["1758", { country: "Saint Lucia", countryCode: "1-758", startsWith: "1758", ISOCode: "LC"}],
	["1767", { country: "Dominica", countryCode: "1-767", startsWith: "1767", ISOCode: "DM"}],
	["1784", { country: "Saint Vincent and the Grenadines", countryCode: "1-784", startsWith: "1784", ISOCode: "VC"}],
	["1787", { country: "Puerto Rico", countryCode: "1-787", startsWith: "1787", ISOCode: "PR"}],
	["1939", { country: "Puerto Rico", countryCode: "1-939", startsWith: "1939", ISOCode: "PR"}],
	["1809", { country: "Dominican Republic", countryCode: "1-809", startsWith: "1809", ISOCode: "DO"}],
	["1829", { country: "Dominican Republic", countryCode: "1-829", startsWith: "1829", ISOCode: "DO"}],
	["1849", { country: "Dominican Republic", countryCode: "1-849", startsWith: "1849", ISOCode: "DO"}],
	["1868", { country: "Trinidad and Tobago", countryCode: "1-868", startsWith: "1868", ISOCode: "TT"}],
	["1869", { country: "Saint Kitts and Nevis", countryCode: "1-869", startsWith: "1869", ISOCode: "KN"}],
	["1876", { country: "Jamaica", countryCode: "1-876", startsWith: "1876", ISOCode: "JM"}],
	["441481", { country: "Guernsey", countryCode: "44-1481", startsWith: "441481", ISOCode: "GG"}],
	["441534", { country: "Jersey", countryCode: "44-1534", startsWith: "441534", ISOCode: "JE"}],
	["441624", { country: "Isle of Man", countryCode: "44-1624", startsWith: "441624", ISOCode: "IM"}]
]);